AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'spec/**/*'
    - 'script/**/*'
    - '**/*.yaml'
    - 'lib/tz_offset/tasks/extract_offsets.rb'
    - 'Rakefile'
    - 'Gemfile'
    - 'tz_offset.gemspec'

Style/AsciiComments:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/AndOr:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Lint/FormatParameterMismatch:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 17

Metrics/ClassLength:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/SignalException:
  EnforcedStyle: semantic
